### ISSUE TITLE
Add further validation before sending to stripe

### ISSUE THREAD

**Issue by bballboy8** [bballboy8/cozy-corners-be#8]
https://github.com/bballboy8/cozy-corners-be/blob/c9201acb863f58db958c2f202570861d7c159621/controller/creditCardController.js#L11C5-L13C6

cardNo should be 16 digits.
cvvCode should be 3–4 digits.
expiryDate must follow MM/YY or MM/YYYY format.

**Comment by chirag-456** [comment]
this is done at the level of payload
